### ISSUE TITLE
question

### ISSUE THREAD

**Issue by GAIYA2050** [Cooper111/Taidi_7th_B#1]
Traceback (most recent call last):
  File "/data1/Taidi_7th_B-master/generate_train.py", line 45, in <module>
    image_slices.sort(key = lambda x: int(x.InstanceNumber), reverse = True)#实验证明！逆序的！
  File "/data1/Taidi_7th_B-master/generate_train.py", line 45, in <lambda>
    image_slices.sort(key = lambda x: int(x.InstanceNumber), reverse = True)#实验证明！逆序的！
  File "/home/amax/anaconda3/envs/tf/lib/python3.6/site-packages/pydicom/dataset.py", line 556, in __getattr__
    return super(Dataset, self).__getattribute__(name)
AttributeError: 'FileDataset' object has no attribute 'InstanceNumber'

**Comment by GAIYA2050** [comment]
运行generate_train.py获得训练集
在这个过程中出现了这个问题
AttributeError: 'FileDataset' object has no attribute 'InstanceNumber'

**Comment by Cooper111** [comment]
你好，刚看到。pydicom得安装最新版本的，建议github源码安装。

**Comment by Cooper111** [comment]
> 运行generate_train.py获得训练集
> 在这个过程中出现了这个问题
> AttributeError: 'FileDataset' object has no attribute 'InstanceNumber'

你好，刚看到。pydicom得安装最新版本的，建议github源码安装
